### PR TITLE
Open image in dialog window

### PR DESCRIPTION
**Pull request by fgervasi**

### CODE REVIEW

**Comment by TiMESPLiNTER** [comment]
I think you need to adjust the base branch here. 😄

**Comment by fgervasi** [comment]
:see_no_evil: Have adjusted it now

**Comment by fgervasi** [comment]
That looks really weird. Is that probably in Firefox? I checked there quickly and couldn't find anything. The bars could be containers for scrollbar. I made a screenshot as it looks for me in the firefox.

image

**Comment by TiMESPLiNTER** [comment]
> That looks really weird. Is that probably in Firefox? I checked there quickly and couldn't find anything. The bars could be containers for scrollbar. I made a screenshot as it looks for me in the firefox.
> 

Yes, I'm using FF

**Comment by fgervasi** [comment]
Issue has been created: #73

**Pull request merged**
